# Change these first
owner: gegeriyadi # Your GitHub organization or username, where this repository lives
repo: server-uptime-monitoring # The name of this repository

sites:
  - name: Gegeriyadi.com
    url: https://gegeriyadi.com
